---
- hosts: localhost
  tasks:
    - stat:
        path: "{{ id_rsa_file }}"
      register: op

    - name: Download pexpect rpm
      get_url:
        url: "http://widehat.opensuse.org/opensuse/distribution/leap/42.3/repo/oss/suse/noarch/python-pexpect-3.3-6.1.noarch.rpm"
        dest: /tmp
        mode: 0755

    - name: Install pexpect
      yum:
        name: /tmp/python-pexpect-3.3-6.1.noarch.rpm
        state: present

    - name: Generating ssh key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}" -q -N "{{ passphrase }}"
      when: op.stat.exists == false

    - debug: 
        msg: "Key pair already exists. Using the same key."
      when: op.stat.exists

    - name: Copy public key to the nodes
      expect:
        command: ssh-copy-id -i "{{ id_rsa_file }}" root@"{{ item }}" -f -o StrictHostKeyChecking=no
        responses:
          'Password': "{{ root_password }}"
      with_items:
        - "{{ nodes }}"

  vars_files:
    - config.yml

